version: 0.2

env:
  variables:
    DATABASE_HOST: "not-used"
    DATABASE_USER: "not-used"
    DATABASE_PASSWORD: "not-used"
    DATABASE_DB_NAME: "not-used"

phases:
  install:
    commands:
      - echo Install started on `date`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'